RedditClone/config/routes.rb
Rails.application.routes.draw do

  resources :comments, only: [:create, :new, :show]
  resources :posts, except: [:index, :destroy]
  resources :subs, except: [:destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :users
end

RedditClone/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :author, :post, presence: true

  belongs_to :parent, class_name: 'Comment'
  belongs_to :author, class_name: 'User'
  belongs_to :post
  has_many :replies, class_name: 'Comment', foreign_key: :parent__comment_id

end

RedditClone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :string
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :author, presence: true
  validate :at_least_one_sub

  belongs_to :author, class_name: 'User'
  has_many :post_subs
  has_many :subs, through: :post_subs
  has_many :comments

  def at_least_one_sub
    unless self.subs.size > 0
      self.errors[:base] << "Must select at least one subforum"
    end
  end

  def top_level_comments
    self.comments.where("parent_comment_id IS NULL")
  end
end

RedditClone/app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :integer          not null, primary key
#  post_id    :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ActiveRecord::Base
  validates :post, :sub, presence: true
  # validates :post_id, uniqueness: { scope: :sub_id }

  belongs_to :post
  belongs_to :sub
end

RedditClone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :description, :moderator, presence: true

  belongs_to :moderator, class_name: 'User'
  has_many :post_subs
  has_many :posts, through: :post_subs
end

RedditClone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, :password_digest, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  has_many :subs, foreign_key: :moderator_id
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id

  attr_reader :password

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil? || !user.is_password?(password)
    user
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def generate_session_token
    SecureRandom::urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token
    self.session_token = generate_session_token
  end
end

RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def log_in(user)
    user.reset_session_token
    session[:session_token] = user.session_token
    user.save
    @current_user = user
  end

  def log_out
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def redirect_if_not_logged_in
    unless logged_in?
      redirect_to new_session_url
    end
  end
end

RedditClone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new(post_id: params[:post_id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.save
    redirect_to post_url(comment_params[:post_id])
  end

  def show
    @comment = Comment.find(params[:id])
  end

  private

    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end
end

RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_posts_author, only: [:edit, :update]

  def new
    @post = Post.new
    @subs = Sub.all
    render :new
  end

  def create
    @subs = Sub.all
    @post = Post.new(post_params)
    @post.author = current_user
    # fail
    unless @post.save
      flash.now[:errors] = @post.errors.full_messages
      render :new
    else
      redirect_to post_url(@post)
    end
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def ensure_posts_author
    @post = Post.find(params[:id])
    unless current_user.id == @post.author_id
      flash[:errors] = ["Can only edit your own post!"]
      redirect_to sub_url(@post.sub)
    end
  end

  def edit
    @post = Post.find(params[:id])
    @subs = Sub.all
  end

  def update
  end

  private

    def post_params
      params.require(:post).permit(:title, :content, :url, sub_ids: [])
    end
end

RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :check_if_already_logged_in, except: [:destroy]

  def new
    @user = User.new
    render :new
  end

  def check_if_already_logged_in
    redirect_to subs_url if logged_in?
  end

  def create
    @user = User.find_by_credentials(user_params[:username], user_params[:password])
    if @user.nil?
      flash.now[:errors] = ["Username and/or password invalid"]
      render :new
    else
      log_in(@user)
      redirect_to subs_url
    end
  end

  def destroy
    log_out
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :redirect_if_not_logged_in
  before_action :ensure_subs_moderator, only: :edit

  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator = current_user
    unless @sub.save
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    else
      redirect_to sub_url(@sub)
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def ensure_subs_moderator
    @sub = Sub.find(params[:id])
    unless current_user.id == @sub.moderator_id
      flash[:errors] = ["Can only edit your own subforum"]
      redirect_to sub_url(@sub)
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
  end

  private

    def sub_params
      params.require(:sub).permit(:title, :description)
    end
end

RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    unless @user.save
      flash.now[:errors] = @user.errors.full_messages
      render :new
    else
      log_in(@user)
      render text: "Logged in as #{@user.username}"
    end
  end

  def new
    @user = User.new
    render :new
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

RedditClone/app/helpers/comments_helper.rb
module CommentsHelper
end

RedditClone/app/helpers/posts_helper.rb
module PostsHelper
end

RedditClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

RedditClone/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

RedditClone/app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<br>

<%= render "shared/errors"  %>

<form action="/posts" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token  %>">
  <label for="post_title">Title</label>
  <input type="text"
         id="post_title"
         name="post[title]"
         value="<%= @post.title %>">
  <br>
   <label for="post_url">URL</label>
   <input type="text"
          id="post_url"
          name="post[url]"
          value="<%= @post.url %>">
  <br>
  <br>
    <label for="post_content">Content</label>
  <br>

  <textarea name="post[content]"
           id="post_content"
           name="post[content]"><%= @post.content %></textarea>

  <!-- Subforums -->

  <h3>Select at least one Subforum...</h3>
    <% @subs.each do |sub| %>
    <input type="checkbox"
           name="post[sub_ids][]"
           id="post_subs_<%= sub.title %>"
           value="<%= sub.id %>"
           <%= "checked" if @post.sub_ids.include?(sub.id) %>>
           <label for="post_subs_<%= sub.title %>"><%= sub.title %></label>
           <br>
    <% end %>

  <br>
  <input type="submit" value="Create Post">
</form>

RedditClone/app/views/posts/new.html.erb
<h1>Create Post</h1>
<br>

<%= render "shared/errors"  %>

<form action="/posts" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token  %>">
  <label for="post_title">Title</label>
  <input type="text"
         id="post_title"
         name="post[title]"
         value="<%= @post.title %>">
  <br>
   <label for="post_url">URL</label>
   <input type="text"
          id="post_url"
          name="post[url]"
          value="<%= @post.url %>">
  <br>
  <br>
    <label for="post_content">Content</label>
  <br>

  <textarea name="post[content]"
           id="post_content"
           name="post[content]"><%= @post.content %></textarea>

  <!-- Subforums -->

  <h3>Select at least one Subforum...</h3>
    <% @subs.each do |sub| %>
    <input type="checkbox"
           name="post[sub_ids][]"
           id="post_subs_<%= sub.title %>"
           value="<%= sub.id %>"
           <%= "checked" if @post.sub_ids.include?(sub.id) %>>
           <label for="post_subs_<%= sub.title %>"><%= sub.title %></label>
           <br>
    <% end %>

  <br>
  <input type="submit" value="Create Post">
</form>

RedditClone/app/views/posts/show.html.erb
<%= render "shared/errors"  %>

<h1><%= @post.title %></h1>



<p><%= @post.url %></p>
<p><%= @post.content %></p>
<p><%= @post.author.username %></p>
<ul><% @post.subs.each do |sub| %>
  <li><%= sub.title %></li>
  <% end %>
</ul>
<br>
<%= link_to "Edit Post", edit_post_url(@post) %>
<%= link_to "Comment", new_comment_url(post_id: @post.id) %>
<br>
<h3>Comments</h3>
<ul>
  <% @post.top_level_comments.each do |par_comment| %>
    <li><%= par_comment.content %></li>
    <li><small><%= par_comment.author.username %></small></li>
  <% end %>
</ul>

RedditClone/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

RedditClone/app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

RedditClone/app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

RedditClone/app/views/subs/index.html.erb
<h1>All Subs</h1>

<ul>

<% @subs.each do |sub| %>
  <li><%= sub.title %></li>
  <li><%= sub.description %></li>
  <br>
<% end %>

</ul>

RedditClone/app/views/subs/new.html.erb
<h1>Create Subforum</h1>
<br>

<%= render "shared/errors"  %>

<form action="/subs" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token  %>">
  <label for="sub_title">Title</label>
  <input type="text"
         id="sub_title"
         name="sub[title]"
         value="<%= @sub.title %>">
   <label for="sub_description">Description</label>
   <input type="description"
          id="sub_description"
          name="sub[description]"
          value="<%= @sub.description %>">
  <input type="submit" value="Create Subforum">
</form>

RedditClone/app/views/subs/show.html.erb
<%= render "shared/errors"  %>

<h1><%= @sub.title %></h1>



<p>
  <%= @sub.description %>
</p>

RedditClone/app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>